name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: checkout to gh pages
      run: git checkout gh-pages
    - name: rebase
      run: git rebase origin/master
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: commit to gh-page
      run: |
        git config --global user.email "bee0060@126.com"
        git config --global user.name "bee0060"
        git commit -am 'Release'
        git push origin gh-pages
      env:
        CI: true
